package com.codequest;
import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api") @CrossOrigin(origins="*")
public class ApiController { private final PlayerRepository repo; ApiController(PlayerRepository repo){this.repo=repo;}
@PostMapping("/register") public Map<String,Object> register(@RequestBody Map<String,String>b){String u=b.getOrDefault("username","").trim(),p=b.getOrDefault("password","");if(u.length()<3||p.length()<4)throw new IllegalArgumentException("Username/password too short");if(repo.findByUsername(u).isPresent())throw new IllegalArgumentException("Username already exists");Player x=new Player();x.username=u;x.passwordHash=p;x.coins=100;repo.save(x);return view(x);}
@PostMapping("/login") public Map<String,Object> login(@RequestBody Map<String,String>b){Player x=repo.findByUsername(b.getOrDefault("username","")).orElseThrow();if(!x.passwordHash.equals(b.getOrDefault("password","")))throw new IllegalArgumentException("Invalid login");return view(x);}
@GetMapping("/players/{username}") public Map<String,Object> player(@PathVariable String username){return view(repo.findByUsername(username).orElseThrow());}
@GetMapping("/leaderboard") public List<Map<String,Object>> leaderboard(){return repo.findTop50ByOrderByXpDesc().stream().map(this::view).toList();}
@PostMapping("/players/{username}/profile") public Map<String,Object> profile(@PathVariable String username,@RequestBody Map<String,String>b){Player x=repo.findByUsername(username).orElseThrow();if(b.containsKey("photoUrl"))x.photoUrl=b.get("photoUrl");if(b.containsKey("title"))x.title=b.get("title");repo.save(x);return view(x);}
@PostMapping("/players/{username}/quest") public Map<String,Object> quest(@PathVariable String username,@RequestBody Map<String,Object>b){Player x=repo.findByUsername(username).orElseThrow();int xp=((Number)b.getOrDefault("xp",0)).intValue(),coins=((Number)b.getOrDefault("coins",0)).intValue();if(xp<0||xp>250||coins<0||coins>500)throw new IllegalArgumentException("Invalid reward");if(x.dailyXp+xp>1000)throw new IllegalArgumentException("Daily XP cap reached");x.xp+=xp;x.dailyXp+=xp;x.coins+=coins;int need=x.level*100+300;while(x.xp>=need){x.xp-=need;x.level++;need=x.level*100+300;}repo.save(x);return view(x);}
private Map<String,Object> view(Player x){Map<String,Object>m=new LinkedHashMap<>();m.put("username",x.username);m.put("photoUrl",x.photoUrl);m.put("level",x.level);m.put("xp",x.xp);m.put("coins",x.coins);m.put("dailyXp",x.dailyXp);m.put("title",x.title);m.put("badges",x.badges);return m;}}
