import React from "react";
import styles from "./_index.module.css";
import { useAuth } from "../helpers/useAuth";
import { useQuery } from "@tanstack/react-query";
import { getDashboard } from "../endpoints/dashboard_GET.schema";

export default function Home() {
 const {authState,logout}=useAuth();
 const dashboard=useQuery({queryKey:["dashboard"],queryFn:getDashboard,enabled:authState.type==="authenticated",staleTime:0});
 const active="Dashboard";
 if(authState.type==="loading") return <main className={styles.authGate}><div className={styles.card}><h1>Loading player profile…</h1></div></main>;
 if(authState.type==="unauthenticated") return <main className={styles.authGate}><div className={styles.card+" "+styles.authCard}><span className={styles.kicker}>// CODEQUEST · GLOBAL SERVER</span><h1>Enter the arena.</h1><p>Create an account or sign in to start your campaign.</p><a className={styles.primaryLink} href="/login">LOGIN / REGISTER →</a></div></main>;
 if(dashboard.isPending) return <main className={styles.authGate}><div className={styles.card}><h1>Loading your command center…</h1></div></main>;
 if(dashboard.isError) return <main className={styles.authGate}><div className={styles.card}><h1>Could not load player data.</h1><p>{dashboard.error instanceof Error?dashboard.error.message:"Unknown error"}</p></div></main>;
 const live=dashboard.data; const me=live.leaderboard.find(x=>x.displayName===live.user.displayName);
 return <main className={styles.shell}><aside className={styles.sidebar}><div className={styles.brand}><span className={styles.brandMark}>CQ</span><div><b>CODEQUEST</b><small>DEVELOPER RPG</small></div></div><nav>{[["Dashboard","/"],["Campaign","/campaign"],["Quests","/quests"],["Bosses","/bosses"],["Projects","/projects"],["Leaderboard","/leaderboard"],["Profile","/profile"],["Shop","/shop"]].map(([item,path])=><a className={item===active?styles.navActive:styles.nav} href={path} key={item}>{item}</a>)}</nav><div className={styles.sidebarFoot}><span>SEASON 01</span><b>JAVA ASCENSION</b><small>Global competition online</small></div></aside>
 <section className={styles.content}><header className={styles.topbar}><div><span className={styles.kicker}>// {active.toUpperCase()}</span><h1>Welcome back, <em>{live.user.displayName}</em></h1></div><div className={styles.topStats}><span>◈ {live.profile.coins.toLocaleString()}</span><span>🔥 {live.profile.streak} DAY</span><button className={styles.avatar} onClick={()=>logout()}>LOG</button></div></header>
 <div className={styles.heroGrid}><section className={styles.card+" "+styles.levelCard}><div className={styles.levelRing+" "+(live.profile.level>=30?styles.frameLegend:live.profile.level>=20?styles.frameGold:live.profile.level>=10?styles.frameSilver:live.profile.level>=5?styles.frameBronze:styles.frameStarter)}><strong>{live.profile.level}</strong><small>LEVEL</small></div><div className={styles.levelInfo}><span className={styles.label}>GLOBAL RANK #{live.leaderboard.find(x=>x.displayName===live.user.displayName)?.rank??"—"}</span><h2>{me?.title??"Code Recruit"}</h2><p>Keep clearing quests to unlock the next combat tier.</p><div className={styles.badgeRow}>{(me?.badges??[]).map(b=><span className={styles.achievement} key={b}>◆ {b}</span>)}</div><div className={styles.xpMeta}><span>{live.profile.xp} XP</span><span>{live.profile.level*1000} XP</span></div><div className={styles.bar}><i style={{width:Math.min(100,(live.profile.xp%1000)/10)+"%"}} /></div></div></section>
 <section className={styles.card+" "+styles.questCard}><div className={styles.cardHead}><span className={styles.label}>NEXT QUEST</span>{live.nextQuest&&<span className={styles.badge}>+{live.nextQuest.xpReward} XP</span>}</div><h2>{live.nextQuest?.title??"Campaign complete"}</h2><p>{live.nextQuest?.description??"You reached the end of the current campaign."}</p>{live.nextQuest&&<a className={styles.primary} href={`/coding-round?questId=${live.nextQuest.id}`}>START CODING →</a>}</section></div>
 <div className={styles.columns}><section><div className={styles.sectionHead}><div><span className={styles.kicker}>// CAMPAIGN</span><h2>Java Ascension</h2></div><span className={styles.muted}>LEVEL {live.profile.level} / 100</span></div><div className={styles.list}>{live.campaign.map(item=><a className={styles.campaign} key={item.level} href={item.locked?"/campaign":`/coding-round?questId=${item.level}`}><span className={styles.num}>{String(item.level).padStart(2,"0")}</span><div className={styles.campMain}><b>{item.title}</b><small>{item.completed?"COMPLETED":item.locked?"LOCKED":"READY"}</small></div><span className={item.locked?styles.lock:styles.live}>{item.completed?"✓":item.locked?"LOCKED":"START"}</span><span>›</span></a>)}</div></section>
 <section><div className={styles.sectionHead}><div><span className={styles.kicker}>// GLOBAL</span><h2>Leaderboard</h2></div><a className={styles.muted} href="/leaderboard">VIEW ALL →</a></div><div className={styles.list}>{live.leaderboard.map(row=><div className={styles.row+(row.displayName===live.user.displayName?" "+styles.you:"")} key={row.rank}><strong>#{row.rank}</strong><span>{row.displayName}</span><small>Lv {row.level} · {row.title}</small><b>{row.badges.length?row.badges[0]:"No badge"}</b></div>)}</div></section></div>
 <section className={styles.card+" "+styles.boss}><div><span className={styles.kicker}>// NEXT BOSS · LEVEL {live.nextBoss?.level ?? "—"}</span><h2>{live.nextBoss?.name ?? "Campaign Complete"}</h2><p>{live.nextBoss ? (live.nextBoss.locked ? "Clear the required levels to unlock this fight." : "The arena is open. Prepare for battle.") : "You cleared the current boss milestones."}</p></div><div className={styles.bossHp}>{live.nextBoss && <><span>{live.nextBoss.locked?"LOCKED":"READY"}</span><div className={styles.hpbar}><i style={{width:live.nextBoss.locked?"0%":"100%"}} /></div><a className={styles.secondary} href="/bosses">{live.nextBoss.locked?"VIEW REQUIREMENTS":"PREPARE BATTLE"}</a></>}</div></section></section></main>;
}
