/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface PlayerProfiles {
  coins: Generated<number>;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  lastXpDate: Timestamp | null;
  level: Generated<number>;
  streak: Generated<number>;
  updatedAt: Generated<Timestamp>;
  userId: Int8;
  xp: Generated<number>;
}

export interface Quests {
  coinReward: Generated<number>;
  description: string;
  id: Generated<Int8>;
  level: number;
  questType: Generated<string>;
  title: string;
  xpReward: number;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface UserQuestProgress {
  completedAt: Generated<Timestamp>;
  id: Generated<Int8>;
  questId: Int8;
  userId: Int8;
}

export interface Users {
  avatarUrl: string | null;
  birthDate: Timestamp | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  loginAttempts: LoginAttempts;
  playerProfiles: PlayerProfiles;
  quests: Quests;
  sessions: Sessions;
  userPasswords: UserPasswords;
  userQuestProgress: UserQuestProgress;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.
